# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nogk3vJFHh9ZQfGaIej2z48kwjHF8nC0
"""

# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Titanic dataset from Seaborn
df = sns.load_dataset('titanic')

# General info
print(df.info())

# Statistical summary
print(df.describe(include='all'))

# Missing values
print("\nMissing Values:\n", df.isnull().sum())

# Histograms for numeric columns
df.hist(figsize=(10, 8), bins=20, edgecolor='black')
plt.suptitle("Histograms of Numeric Features", fontsize=16)
plt.tight_layout()
plt.show()

# Boxplots
numeric_cols = ['age', 'fare']
for col in numeric_cols:
    sns.boxplot(data=df, x=col)
    plt.title(f'Boxplot of {col}')
    plt.show()

# Correlation heatmap (only numeric features)
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

# Pairplot with hue by survival
sns.pairplot(df[['survived', 'age', 'fare', 'pclass']], hue='survived', diag_kind='kde')
plt.suptitle("Pairplot of Selected Features", y=1.02)
plt.show()

# Survival by gender
sns.countplot(data=df, x='sex', hue='survived')
plt.title("Survival Count by Gender")
plt.show()

# Survival by class
sns.countplot(data=df, x='pclass', hue='survived')
plt.title("Survival Count by Passenger Class")
plt.show()

# Age distribution by survival
sns.kdeplot(data=df, x='age', hue='survived', common_norm=False, fill=True)
plt.title("Age Distribution by Survival")
plt.show()

